version: '3.8'
services:

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - .mongodb/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped


  todo-backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - 4000:4000
    links:
      - mongodb

  todo-frontend:
    build: ./
    container_name: todo-frontend
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    links:
      - todo-backend
    ports:
      - 3000:3000
    stdin_open: true
    # environment:
    #   - CHOKIDAR_USEPOLLING=true

#   kanban-ui:
#     build: ./kanban-ui
#     container_name: kanban-ui
#     ports:
#       - 4200:80
#     links:
#       - kanban-app


volumes:
  kanban-data:
